### ISSUE TITLE
Needs to be built for ES5 / production

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stamp-utils#2]
- [Webpack Example](https://github.com/cloverfield-tools/cf-package/tree/master/template)

**Comment by ericelliott** [comment]
@nkbt It would be really cool if we had those composable cf modules, right? ;)

**Comment by nkbt** [comment]
I guess so, but not sure I get it right. I do not use StampIt so completely unfamiliar with its tooling

**Comment by ericelliott** [comment]
We're building for ES5 now, but composable cf modules are still a good idea for other projects. =)
